Tests rspec
josuerushanika/OOP-school-library pull request #8
Opened 2023-05-10 13:29 UTC by josuerushanika

In this branch me and @obed300 ;

Added below unit tests:
Book
Person
Student
Teacher
Classroom
Rental
Decorator
Capitalize decorator
Trimmer decorator

2023-05-10 13:59 UTC, BregornOriginal requested changes
Hi @josuerushanika  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![cat-driving-serious](https://github.com/josuerushanika/OOP-school-library/assets/93630700/89f1c97c-26dc-41a5-8f92-e59fc18e7c9c)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ README looks professional

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/base_decorator_spec.rb
> +end
- [ ] Kindly check this test, it's not working

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/capitalize_decorator_spec.rb
> +end
- [ ] Kindly check this test, it's not working

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/classroom_spec.rb
> +end
- [ ] Kindly check this test, it's not working

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/nameable_spec.rb
> +end
- [ ] Kindly check this test, it's not working

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/person_spec.rb
> +end
- [ ] Kindly check this test, it's not working

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/rental_spec.rb
> +end
- [ ] Kindly check this test, it's not working

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/student_spec.rb
> +describe Student do
- [ ] Kindly check this test, it's not working

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/teacher_spec.rb
> +describe Teacher do
- [ ] Kindly check this test, it's not working

2023-05-10 13:59 UTC, BregornOriginal commented on data/spec/trimmer_decorator_spec.rb
> +describe TrimmerDecorator do
- [ ] Kindly check this test, it's not working

2023-05-11 10:33 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @josuerushanika and @obed300 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- All tests are now passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 10:37 UTC, merged

2023-07-23 13:37 UTC, josuerushanika commented
Thank You